name: print_script
description: "Share your code with the world!"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  responsive_builder:
  shadcn_ui:
  icons_plus:
  cupertino_icons: ^1.0.8
  path:
  google_fonts:
  desktop_drop: ^0.5.0
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.3
  file_saver: ^0.2.14
  path_provider:
  autotrie: ^2.0.0
  characters: ^1.2.1
  charcode: ^1.3.1
  collection: ^1.17.2
  equatable: ^2.0.5
  dartx:
  meta: ^1.9.1
  mocktail: ^1.0.1
  scrollable_positioned_list: ^0.3.5
  tuple: ^2.0.1
  url_launcher: ^6.1.8
  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
